import type { NotaryPageData } from '../types/wagtail';

export const mockNotaryData: NotaryPageData = {
  id: 1,
  title: 'Professional Notary Services',
  meta: {
    type: 'notary.NotaryPage',
    slug: 'home',
    seo_title: 'Professional Notary Services - Certified & Trusted',
    search_description: 'Licensed notary public offering mobile, office, and remote online notarization services.',
  },
  color_theme: {
    id: 1,
    name: 'Professional Blue',
    primary_color: '#2563eb',
    secondary_color: '#1e40af',
    accent_color: '#f59e0b',
    neutral_color: '#6b7280',
    background_color: '#ffffff',
    text_color: '#1f2937',
  },
  blocks: [
    {
      type: 'hero',
      value: {
        headline: 'Trusted Notary Services at Your Convenience',
        subheadline: 'Professional, certified notary public serving your community with mobile, office, and remote online notarization.',
        primary_cta_label: 'Book Appointment',
        primary_cta_action: 'book',
        secondary_cta_label: 'Learn More',
        secondary_cta_action: 'contact',
        background_type: 'gradient',
        show_location_badge: true,
        location_text: '📍 Serving California',
      },
      id: 'hero-1',
    },
    {
      type: 'verified_credentials',
      value: {
        notary_name: 'John Smith',
        state_of_commission: 'California',
        license_number: 'CA-123456789',
        commission_expiry: '2026-12-31',
        certifications: [
          'NNA Certified',
          'Background Screened',
          'RON Authorized',
          'E&O Insured',
        ],
        display_badge_icons: true,
        disclaimer_text: 'Licensed and bonded notary public in the State of California. Commission number CA-123456789.',
      },
      id: 'credentials-1',
    },
    {
      type: 'services_list',
      value: {
        services: [
          {
            service_name: 'Mobile Notary',
            description: '. Basic Notarial Acts,\r\n. Loan Contact Forms,\r\n. Living Trust,\r\n. Mortages',
            starting_price: 'Starting at $50',
            duration: '20-60 minutes',
            cta_label: 'Schedule Visit',
            cta_action: 'contact',
            is_popular: true,
          },
          {
            service_name: 'Copy Certification',
            description: 'A copy certification confirms that a photocopy is a true and accurate copy of an original document. Commonly used for IDs, passports (where allowed), diplomas, and records. Availability depends on state laws.',
            starting_price: '',
            duration: '',
            cta_label: '',
            cta_action: 'contact',
            is_popular: false,
          },
          {
            service_name: 'Real Estate Transaction',
            description: 'Includes notarization of real estate documents such as deeds, mortgages, refinance packages, and closing disclosures. A certified Notary Signing Agent ensures documents are properly signed, dated, and notarized for lenders and title companies.',
            starting_price: '',
            duration: '',
            cta_label: '',
            cta_action: 'contact',
            is_popular: false,
          },
          {
            service_name: 'Power of Attorney',
            description: 'A Power of Attorney allows one person to legally act on behalf of another. The notary verifies identity, willingness, and awareness of the signer to help prevent fraud and ensure legal validity.',
            starting_price: '',
            duration: '',
            cta_label: '',
            cta_action: 'contact',
            is_popular: false,
          },
          {
            service_name: 'Mobile Notary Services Available',
            description: "Whether you're at home, in the office, or at a location that's convenient for you, our certified notaries will come to you. We aim to make notarizing documents a hassle-free experience, offering services that fit into your busy schedule.\r\n\r\nService Solutions\r\n✅ Flexible Scheduling\r\n✅ Affordable Rates\r\n✅ Convenience\r\n✅ Quick Turnaround\r\n✅ Document Notarization\r\n✅ Mobile Services\r\n✅ Certified & Experienced Notaries\r\n✅ Affordable Packages",
            starting_price: '',
            duration: '',
            cta_label: '',
            cta_action: '',
            is_popular: false,
          },
          {
            service_name: 'Notary Public Services',
            description: 'De La Cruz Dispatch & Notary Services LLC offers professional mobile notary public services available 24/7. Our certified notaries come directly to your location—home, office, or anywhere convenient—to handle document notarization quickly and reliably. We specialize in affidavits, powers of attorney, contracts, wills, trusts, loan forms, mortgages, and basic notarial acts, ensuring a hassle-free experience every time.',
            starting_price: '',
            duration: '',
            cta_label: '',
            cta_action: '',
            is_popular: false,
          },
          {
            service_name: 'Mobile Notary Services',
            description: 'Our Services:\r\n✅ Basic Notarial Acts\r\n✅ Loan Contract Forms\r\n✅ Living Trust\r\n✅ Mortgages',
            starting_price: '',
            duration: '',
            cta_label: '',
            cta_action: '',
            is_popular: false,
          },
          {
            service_name: 'Immigration Services',
            description: 'We provide expert notarization support for immigration-related documents to make your process smoother. Our experienced notaries assist with affidavits of support, document translations, applications, and other forms requiring official certification. Please note that we handle notarization only and do not offer legal advice—our focus is on fast, accurate, and professional mobile service',
            starting_price: '',
            duration: '',
            cta_label: '',
            cta_action: '',
            is_popular: false,
          },
          {
            service_name: 'Bookkeeping Services',
            description: 'Our affordable bookkeeping services help individuals and small businesses maintain organized and accurate financial records. We offer reliable support for tracking expenses, income, invoicing, and basic financial management tailored to your needs. With flexible scheduling and mobile options, we make it easy to keep your books in order without disrupting your busy schedule.',
            starting_price: '',
            duration: '',
            cta_label: '',
            cta_action: '',
            is_popular: false,
          },
          {
            service_name: 'Roadside Services',
            description: "When you're stranded and need immediate help, our unique roadside notary combination gets you back on track fast. We provide quick roadside assistance along with on-the-spot notary services for any related documents, such as insurance forms or accident reports. Available anytime, anywhere, we bring professional support directly to you during unexpected situations.",
            starting_price: '',
            duration: '',
            cta_label: '',
            cta_action: '',
            is_popular: false,
          },
        ],
      },
      id: 'services-1',
    },
    {
      type: 'service_area',
      value: {
        service_modes: ['office', 'mobile', 'remote'],
        cities_served: [
          'Los Angeles',
          'San Diego',
          'San Francisco',
          'Sacramento',
          'San Jose',
          'Fresno',
        ],
        travel_radius: 50,
        show_map: true,
        map_type: 'google',
        office_address: '123 Main Street, Los Angeles, CA 90001',
      },
      id: 'service-area-1',
    },
    {
      type: 'booking',
      value: {
        booking_type: 'office',
        calendar_source: 'internal',
        duration_options: ['15 min', '30 min', '60 min'],
        buffer_time: 15,
        require_payment: false,
        confirmation_message: 'You will receive a confirmation email shortly.',
      },
      id: 'booking-1',
    },
    {
      type: 'document_upload',
      value: {
        allowed_file_types: ['.pdf', '.jpg', '.png', '.docx'],
        max_file_size: 10,
        require_before_booking: false,
        instructions: 'Upload your documents securely. All files are encrypted and stored safely.',
        privacy_notice: 'Your documents are encrypted using 256-bit SSL encryption and stored securely. We never share your information with third parties.',
      },
      id: 'upload-1',
    },
    {
      type: 'testimonials',
      value: {
        display_type: 'manual',
        testimonials: [
          {
            client_name: 'Apple',
            rating: 5,
            testimonial_text: 'People work for us',
            client_photo: {
              id: 8,
              title: 'images (1)',
              url: '/media/original_images/images_1.jpeg',
            },
          },
          {
            client_name: 'WeAssure Screening Services',
            rating: 5,
            testimonial_text: 'dshbfkdshfjkdshfkjdhfkjdhfsdhjkdgjk;dfghdfjkghfdjkhgjkdfghjkdfhgjkdfhg',
            client_photo: {
              id: 247,
              title: 'cr=w_989,h_1000',
              url: '/media/original_images/crw_989h_1000.webp',
            },
          },
        ],
        max_reviews: 3,
      },
      id: 'testimonials-1',
    },
    {
      type: 'faq',
      value: {
        category: 'General',
        faqs: [
          {
            question: 'What documents do I need to bring?',
            answer: 'You need a valid government-issued photo ID (driver\'s license, passport, or state ID) and the documents to be notarized. The documents should be unsigned.',
          },
          {
            question: 'How much does notarization cost?',
            answer: 'California law sets the maximum fee at $15 per signature for most documents. Mobile notary services start at $75 which includes travel. RON services start at $25.',
          },
          {
            question: 'Do you offer mobile notary services?',
            answer: 'Yes! We come to your location anywhere within 50 miles. Perfect for home closings, hospital visits, or office signings.',
          },
          {
            question: 'What is Remote Online Notarization (RON)?',
            answer: 'RON allows you to get documents notarized via secure video call. It\'s legal in California and available 24/7 for your convenience.',
          },
          {
            question: 'How long does the notarization process take?',
            answer: 'Most notarizations take 15-30 minutes. Loan signings typically take 60-90 minutes. We always schedule enough time to answer your questions.',
          },
        ],
        expand_first: true,
      },
      id: 'faq-1',
    },
    {
      type: 'payment',
      value: {
        payment_type: 'full',
        amount: '15.00',
        description: 'Secure payment for notary services',
        require_before_proceeding: false,
        success_message: 'Payment successful! Your appointment is confirmed.',
      },
      id: 'payment-1',
    },
    {
      type: 'contact_form',
      value: {
        form_fields: ['name', 'email', 'phone', 'message'],
        enable_file_upload: true,
        route_to: 'email',
        success_message: 'Thank you for contacting us! We\'ll respond within 24 hours.',
      },
      id: 'contact-1',
    },
  ],
  footer_config: {
    name: 'Notary Services',
    company_info: {
      description: 'Professional notary services you can trust.',
      logo: null,
    },
    contact_info: {
      address: '123 Main Street, Los Angeles, CA 90001',
      phone: '(555) 123-4567',
      email: 'contact@notaryservices.com',
    },
    social_links: [
      {
        platform: 'Facebook',
        url: 'https://www.facebook.com/people/WeAssure-Screening-Services/61575534218707/',
        icon_class: 'fab fa-facebook',
      },
      {
        platform: 'Twitter',
        url: 'https://x.com/WeAssureKC',
        icon_class: 'fab fa-twitter',
      },
      {
        platform: 'LinkedIn',
        url: 'https://www.linkedin.com/company/weassure-biometrics-and-screening-services',
        icon_class: 'fab fa-linkedin',
      },
      {
        platform: 'Instagram',
        url: 'https://www.instagram.com/weassurekc',
        icon_class: 'fab fa-instagram',
      },
      {
        platform: 'YouTube',
        url: 'https://www.youtube.com/@weassurekc',
        icon_class: 'fab fa-youtube',
      },
    ],
    sections: {
      quick_links: {
        show: true,
        heading: 'Quick Links',
        links: [
          { name: 'Home', url: '#', order: 1 },
          { name: 'About', url: '#', order: 2 },
          { name: 'Services', url: '#services-1', order: 3 },
        ],
      },
      services: {
        show: false,
        heading: 'Services',
        links: [],
      },
      resources: {
        show: true,
        heading: 'Resources',
        links: [
          { name: 'FAQ', url: '#faq-1', order: 1 },
          { name: 'Privacy Policy', url: '#', order: 2 },
        ],
      },
      contact: {
        show: true,
        heading: 'Contact Us',
      },
    },
    copyright_text: '© 2024 Notary Services. All rights reserved.',
    additional_footer_text: '',
  },
};
