#!/bin/bash

echo "🚀 Notary Template - React + TypeScript + Tailwind CSS"
echo "======================================================"
echo ""
echo "✅ Project created successfully!"
echo ""
echo "📦 Installed packages:"
npm list --depth=0
echo ""
echo "🎯 Available commands:"
echo "  npm run dev     - Start development server"
echo "  npm run build   - Build for production"
echo "  npm run preview - Preview production build"
echo ""
echo "🔧 Features included:"
echo "  ✓ Hero Block"
echo "  ✓ Verified Credentials Block"
echo "  ✓ Services List Block"
echo "  ✓ Booking Block"
echo "  ✓ Document Upload Block"
echo "  ✓ Payment Block (Stripe ready)"
echo "  ✓ FAQ Block"
echo "  ✓ Testimonials Block"
echo "  ✓ Service Area Block"
echo "  ✓ eSignature Block"
echo "  ✓ Identity Verification Block"
echo "  ✓ Consent Block"
echo "  ✓ Contact Form Block"
echo "  ✓ Content Block"
echo ""
echo "📚 Documentation: See README.md"
echo "🌐 Wagtail Integration: Configured for /api/v2/notary-pages/"
echo "🎨 Mock Data: Available for development testing"
echo ""
echo "To get started:"
echo "  cd notary-template"
echo "  npm run dev"
